BASE <https://id.example.org/>
PREFIX : <https://id.example.org/schema/>

CONSTRUCT {
    <Activities> :activities ?activity .
    ?activity
        :app ?app ;
        :name ?title ;
        :cause ?cause ;
    .

    ?app :name ?name .
  
    ?cause :name ?causeName ; :app ?causeApp .
  
    ?causeApp :name ?causeAppName .
}
WHERE {
    ?activity
        :activityApp ?app ;
        :activityLabel ?title ;
        :activityCause ?cause ;
    .

    ?app :appName ?name .
  
    ?causeApp :appName ?causeAppName .
    ?cause :optionDisplayName ?causeName ; :optionApp ?causeApp .
}
