BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

CONSTRUCT {
    ?organisation
        a :Organisation ;
        :name ?label ;
        :description ?description ;
        :purpose ?purpose ;
        :website ?website ;
    .
}
WHERE {
    FILTER(?organisation = IRI($id))
    ?organisation
        :organisationLabel ?label ;
        :organisationDescription ?description ;
        :organisationPurpose ?purpose ;
        :organisationUrl ?website ;
    .
}
