BASE <https://id.example.org/>
PREFIX : <https://id.example.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?vocabularyClass ?vocabularyClassProperty ?vocabularyClassValue .
    ?vocabularyObjectProperty ?vocabularyObjectPropertyProperty ?vocabularyObjectPropertyValue .
}
WHERE {
    ?vocabularyClass
        a owl:Class ;
        ?vocabularyClassProperty ?vocabularyClassValue ;
    .

    FILTER NOT EXISTS {
        ?vocabularyClass rdfs:subClassOf ?vocabularyClassValue .
    }

    ?vocabularyObjectProperty
        a owl:ObjectProperty ;
        ?vocabularyObjectPropertyProperty ?vocabularyObjectPropertyValue ;
    .
}
