PREFIX : <https://id.volunteeringdata.io/schema/>
PREFIX text: <http://jena.apache.org/text#>

SELECT ?s ?label ?value
WHERE {
  (?s ?score ?value) text:query (:organizationDescription :organizationLabel :organizationPurpose $query "highlight:s:<mark>|e:</mark>") .
  
  ?s :organizationLabel ?label .
}
ORDER BY DESC(?score)
