BASE <https://id.example.org/>
PREFIX : <https://id.example.org/schema/>

CONSTRUCT {
    <Organisations> :organisations ?organisation .
    ?organisation :name ?orgLabel .
}
WHERE {
    ?organisation :organizationLabel ?orgLabel .
    FILTER CONTAINS(lcase(?orgLabel), lcase($name))
}
