BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>
PREFIX text: <http://jena.apache.org/text#>

CONSTRUCT {
    <Organisations> :organisations ?organisation .

    ?organisation
        a :Organisation ;
        :label ?label ;
        :indexMatchingScore ?score ;
    .
}
WHERE {
  
    (?organisation ?score ?value) text:query (:organisationLabel $name) .
    ?organisation
      :organisationLabel ?label ;
    .
}
ORDER BY ASC(?score)
