BASE <https://id.example.org/>
PREFIX : <https://id.example.org/schema/>
PREFIX text: <http://jena.apache.org/text#>

CONSTRUCT {
    <Organisations> :organisations ?organisation .
    ?organisation :label ?orgLabel .
}
WHERE {
    ?organisation
      text:query (:organisationLabel $name) ;
      :label ?orgLabel ;
    .
}
