BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

CONSTRUCT {
    :ConceptScheme
        :label ?label ;
        :description ?description ;
        :topConcept ?topConcept ;
    .

    ?topConcept :label ?topConceptLabel .

    ?concept
        a ?topConcept ;
        :label ?conceptLabel ;
    .
}
WHERE {
    :ConceptScheme
        :label ?label ;
        :description ?description ;
        :topConcept ?topConcept ;
    .

    ?topConcept :label ?topConceptLabel .

    ?concept
        a ?topConcept ;
        :label ?conceptLabel ;
    .
}
