BASE <https://id.example.org/schema/>
PREFIX : <https://id.example.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?vocabularyClass ?vocabularyClassProperty ?vocabularyClassValue .
    ?vocabularyProperty ?vocabularyPropertyProperty ?vocabularyPropertyValue .
    ?vocabularyPropertyValue rdfs:label ?vocabularyClassLabel .
}
WHERE {
    FILTER(?vocabularyClass = IRI($class))
    FILTER(?vocabularyPropertyProperty != IRI(rdfs:subPropertyOf))
    FILTER(?vocabularyPropertyProperty != IRI(owl:inverseOf))

    ?vocabularyClass ?vocabularyClassProperty ?vocabularyClassValue .
      
    ?vocabularyProperty
      rdfs:domain ?vocabularyClass ;
      ?vocabularyPropertyProperty ?vocabularyPropertyValue .

    OPTIONAL {
        ?vocabularyPropertyValue
            rdfs:label ?vocabularyClassLabel ;
            a owl:Class .
    }
}
