BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

CONSTRUCT {
    ?activity
        a :Activity ;
        :app ?app ;
        :label ?title ;
        :cause ?causeName  ;
        :requirement ?requirementName ;
    .

    ?app :name ?name .

    # ?cause a :Cause ; :label ?causeName ; :xxx ?causeName .

    ?causeApp :name ?causeAppName .
}
WHERE {
    FILTER(?activity = IRI($id))
    ?activity
        :activityApp ?app ;
        :activityLabel ?title ;
        :activityCause ?cause ;
        :activityRequirement ?requirement ;
    .

    ?app :appName ?name .
  
    ?causeApp :appName ?causeAppName .
    ?cause :optionDisplayName ?causeName ; :optionApp ?causeApp .

    ?requirement :optionDisplayName ?requirementName .
}

# SELECT *
# WHERE {
#     ?activity
#         :activityAttendees ?attendees ;
#         :activityBookings ?bookings ;
#         :activityDeleted ?deleted ;
#         :activityEcosystem ?ecosystem ;
#         :activityOrganisation ?organisation ;
#         :activityPublishedApps ?publishedApps ;
#         :activityLabel ?title ;
#         :activityDescription ?description ;
#         :activityType ?type ;
#         :activityLocationOption ?locationOption ;
#         :activityApp ?app ;
#         :activityMeasurementUnit ?measurementUnit ;
#         :activityCause ?cause ;
#     .

#     OPTIONAL { ?activity :activityDue ?due . }
#     OPTIONAL { ?activity :activityEnd ?end . }
#     OPTIONAL { ?activity :activityExternalApplyLink ?externalApplyLink . }
#     OPTIONAL { ?activity :activityIsOnline ?isOnline . }
#     OPTIONAL { ?activity :activityIsVolunteerNumberLimited ?isVolunteerNumberLimited . }
#     OPTIONAL { ?activity :activityMeeting ?meeting . }
#     OPTIONAL { ?activity :activityStart ?start . }
#     OPTIONAL { ?activity :activityVolunteers ?volunteers . }
#     OPTIONAL { ?activity :activityEventType ?eventType . }
#     OPTIONAL { ?activity :activityRequirement ?requirement . }
#     OPTIONAL { ?activity :activityAddress ?address . }
#     OPTIONAL { ?activity :activityLatitude ?latitude . }
#     OPTIONAL { ?activity :activityLongitude ?longitude . }
#     OPTIONAL { ?activity :activityRegion ?region . }
# }
