BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>
PREFIX id: <https://id.volunteeringdata.io/>

CONSTRUCT {
    ?activity
        a :Activity ;
        :label ?activityLabel ;
        :organisation ?activityOrganisation ;
        :description ?activityDescription ;
        :activityApplyLink ?activityApplyLink ;
        :location ?activityLocation ;
        :contact ?activityContact ;
        :cause ?activityCause ;
    .

    ?activityOrganisation :label ?activityOrganisationLabel .

    ?activityLocation
        :locationType ?locationType ;
        :address ?address ;
        :latitude ?latitude ;
        :longitude ?longitude ;
    .

    ?activityContact
        :email ?contactEmail ;
        :phone ?contactPhone ;
    .

    ?activityCause :label ?causeLabel .
}
WHERE {
    FILTER(?activity = IRI($id))
    ?activity
        a :Activity ;
        :label ?activityLabel ;
        :organisation ?activityOrganisation ;
    .

    ?activityOrganisation :label ?activityOrganisationLabel .

    OPTIONAL { ?activity :activityDescription ?activityDescription . }
    OPTIONAL { ?activity :activityApplyLink ?activityApplyLink . }
    OPTIONAL {
        ?activity :location ?activityLocation .
        OPTIONAL { ?activityLocation :locationType ?locationType . }
        OPTIONAL { ?activityLocation :address ?address . }
        OPTIONAL { ?activityLocation :latitude ?latitude . }
        OPTIONAL { ?activityLocation :longitude ?longitude . }
    }
    OPTIONAL {
        ?activity :activityContact ?activityContact .
        OPTIONAL { ?activityContact :email ?contactEmail . }
        OPTIONAL { ?activityContact :phone ?contactPhone . }
    }
    OPTIONAL {
        ?activity :cause ?activityCause .
        ?activityCause :label ?causeLabel .
    }
}


# SELECT *
# WHERE {
#     ?activity
#         :activityAttendees ?attendees ;
#         :activityBookings ?bookings ;
#         :activityDeleted ?deleted ;
#         :activityEcosystem ?ecosystem ;
#         :activityOrganisation ?organisation ;
#         :activityPublishedApps ?publishedApps ;
#         :activityLabel ?title ;
#         :activityDescription ?description ;
#         :activityType ?type ;
#         :activityLocationOption ?locationOption ;
#         :activityApp ?app ;
#         :activityMeasurementUnit ?measurementUnit ;
#         :activityCause ?cause ;
#     .

#     OPTIONAL { ?activity :activityDue ?due . }
#     OPTIONAL { ?activity :activityEnd ?end . }
#     OPTIONAL { ?activity :activityExternalApplyLink ?externalApplyLink . }
#     OPTIONAL { ?activity :activityIsOnline ?isOnline . }
#     OPTIONAL { ?activity :activityIsVolunteerNumberLimited ?isVolunteerNumberLimited . }
#     OPTIONAL { ?activity :activityMeeting ?meeting . }
#     OPTIONAL { ?activity :activityStart ?start . }
#     OPTIONAL { ?activity :activityVolunteers ?volunteers . }
#     OPTIONAL { ?activity :activityEventType ?eventType . }
#     OPTIONAL { ?activity :activityRequirement ?requirement . }
#     OPTIONAL { ?activity :activityAddress ?address . }
#     OPTIONAL { ?activity :activityLatitude ?latitude . }
#     OPTIONAL { ?activity :activityLongitude ?longitude . }
#     OPTIONAL { ?activity :activityRegion ?region . }
# }
