BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

CONSTRUCT {
    ?activity
        a :Activity ;
        :app ?app ;
        :label ?title ;
        :cause ?causeName  ;
        :requirement ?requirementName ;
    .

    ?app :name ?name .

    # ?cause a :Cause ; :label ?causeName ; :xxx ?causeName .

    ?causeApp :name ?causeAppName .
}
WHERE {
    FILTER(?activity = IRI($id))
    ?activity
        :activityApp ?app ;
        :activityLabel ?title ;
        :activityCause ?cause ;
        :activityRequirement ?requirement ;
    .

    ?app :appName ?name .
  
    ?causeApp :appName ?causeAppName .
    ?cause :optionDisplayName ?causeName ; :optionApp ?causeApp .

    ?requirement :optionDisplayName ?requirementName .
}
