BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>
PREFIX cr: <http://mlcommons.org/croissant/>
PREFIX schema: <https://schema.org/>
PREFIX dc: <http://purl.org/dc/terms/>

CONSTRUCT {
    [
        a schema:Dataset ;
        cr:recordSet [
            a cr:RecordSet ;
            cr:dataType :Activity ;
            cr:field :activityDescription ;
            cr:field :activityTitle ;
        ] ;

        cr:recordSet [
            a cr:RecordSet ;
            cr:dataType :Organisation ;
            cr:field :organisationDescription ;
            cr:field :organisationName ;
        ] ;

        dc:conformsTo "http://mlcommons.org/croissant/1.0"@en ;
        schema:creator "Open Volunteering"@en ;
        schema:datePublished "2025-11-07"@en ;
        schema:description "Volunteering and social action opportunities in the UK"@en ;
        schema:distribution [
            a cr:FileObject ;
            schema:contentUrl "https://query20251112104247-h6affebdd4gfa4bs.uksouth-01.azurewebsites.net/all_activities.csv"@en ;
            schema:encodingFormat "text/csv"@en ;
            schema:name "all_activities.csv"@en ;
        ] ;

        schema:license "https://creativecommons.org/licenses/by/4.0/"@en ;
        schema:name "Volunteering and social action opportunities in the UK"@en ;
        schema:url "https://example.org/opportunities"@en ;
    ] .

    :activityDescription a cr:Field .
    :activityTitle a cr:Field .
    :organisationDescription a cr:Field .
    :organisationName a cr:Field .
}
WHERE {}
