BASE <https://id.example.org/>
PREFIX : <https://id.example.org/schema/>

SELECT *
WHERE {
    ?app
        :appDescription ?description ;
        :appEcosystem ?ecosystem ;
        :appLogo ?logo ;
        :appName ?name ;
        :appOrganisation ?organisation ;
    .

    OPTIONAL { ?app :appBrandColor ?brandColor . }
}
