BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

CONSTRUCT {
    <Causes> :causes ?cause .

    ?cause
        :label ?label ;
    .
}
WHERE {
    ?activity :activityCause ?cause .

    ?cause
        :optionDisplayName ?label ;
    .
}
