BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?vocabularyResource ?vocabularyResourceProperty ?vocabularyResourceValue .
}
WHERE {
    ?vocabularyResource
        ?vocabularyResourceProperty ?vocabularyResourceValue ;
        rdfs:isDefinedBy :schema .
}
