BASE <https://id.volunteeringdata.io/>
PREFIX : <https://id.volunteeringdata.io/schema/>

SELECT *
WHERE {
    ?measurementUnit
        :measurementUnitCategory ?unitCategory ;
        :measurementUnitPluralLabel ?unitPluralLabel ;
        :measurementUnitSingularLabel ?unitSingularLabel ;
    .
}
